# Generated by Django 2.2.5 on 2020-01-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newField',
            field=models.TextField(default=''),
        ),
    ]
