# Generated by Django 2.2.5 on 2020-01-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200128_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='king',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=140),
        ),
    ]
