# Generated by Django 2.2.5 on 2020-01-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200129_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='king',
        ),
    ]
